SELECT 
  "UPDATED_DT", 
  "PROVINCE",
  "PROPERTY_TYPE", 
  "SIZE_GROUP",
  COUNT(*) AS COUNT,
  MIN("PRICE_UF") AS MIN_UF,
  MAX("PRICE_UF") AS MAX_UF,
  CEIL(AVG("PRICE_UF")) AS AVG_UF,
  SUM("PRICE_UF") AS TOTAL_UF,
  to_char (SUM("PRICE_UF")*28800,'$ 99 999 999 999 999 990') AS TOTAL_CLP
FROM 
  houses_v2 
WHERE 
  "STAGE"='out'
GROUP BY
  "UPDATED_DT", 
  "PROVINCE",
  "PROPERTY_TYPE", 
  "SIZE_GROUP"
ORDER BY 
  COUNT DESC
;