# Dashboards configuration file
dataFolder: D:/Reference/housemodel/data/DASH/python
# SQL scripts
createMarketView: D:\Reference\housemodel\main\DASH\sql\create_house_market_v2.sql
selectMarketView: D:\Reference\housemodel\main\DASH\sql\select_house_market_v2.sql
## Group
groupLib: D:\Reference\housemodel\main\DASH\houseMarket.py
# Stats
statsPath: D:/Reference/housemodel/stats/DASH
# Setup
dbCfg:
  db: houses
  user: postgres
  hst: localhost
  prt: 5432
# Execution setup
info: False
force: False
stats: True
debug: True
# Author details
version: 2
author:
  alias: Brownbull
  name: Gabriel Carcamo
  email: carcamo.gabriel@gmail.com
