# Transformation configuration file
# Input Setup
dataIndex: D:/Reference/housemodel/data/E/byHand/segment1_dataSources.csv
dataFolder: D:/Reference/housemodel/data/E/webscrapper
dataSrces: &dataSrces [ 'portal inmobiliario', 'toctoc', 'propiedades emol', 'icasas' ]
# Processing Initial Date format YYYYMMDD
procDtIni: 20200701
# Processing End Date format YYYYMMDD
procDtEnd: 20210101
# Stats
statsPath: D:\Reference\housemodel\stats\ETL
# Extract Setup
# Transform Setup
transformPath: D:\Reference\housemodel\data\T\ETL
## Collect
collectLib: D:\Reference\housemodel\main\ETL\T\houses\collect.py
collectionCols: [Srce, Province, PublishedDate, PropertyType, PropertyState, MtTot, Bdroom, Bath, Parking,  PriceUF, Link, Description]
## Format
formatLib: D:\Reference\housemodel\main\ETL\T\houses\format.py
formatCols: [Srce, Province, PublishedDate, PropertyType, PropertyState, MtTot, Bdroom, Bath, Parking,  PriceUF, Link]
## Fill
fillLib: D:\Reference\housemodel\main\ETL\T\houses\fill.py
fillCols: [Srce, Province, PublishedDate, PropertyType, PropertyState, MtTot, Bdroom, Bath, Parking,  PriceUF, Link]
# Execution setup
info: False
force: False
stats: True
debug: True
# Author details
version: 1
author:
  alias: Brownbull
  name: Gabriel Carcamo
  email: carcamo.gabriel@gmail.com
