# Transformation configuration file
# Input Setup
dataIndex: D:/Reference/housemodel/data/E/byHand/segment1_dataSources.csv
dataFolder: D:/Reference/housemodel/data/E/webscrapper
dataSrces: &dataSrces [ 'portal inmobiliario', 'toctoc', 'propiedades emol', 'icasas', 'chile propiedades' ]
# Processing Initial Date format YYYYMMDD
procDtIni: 20200701
# Processing End Date format YYYYMMDD
procDtEnd: 20210101
# Extract Setup
# Transform Setup
etlTransformLib: D:\Reference\housemodel\main\ETL\T4houses.py
etlTransformCols: [Srce, Province, PublishedDate, PropertyType, PropertyState, MtTot, Bdroom, Bath, Parking,  PriceUF, Link]
etlTransformPath: D:\Reference\housemodel\data\T\ETL
# Execution setup
info: False
force: False
stats: True
debug: True
# Author details
version: 1
author:
  alias: Brownbull
  name: Gabriel Carcamo
  email: carcamo.gabriel@gmail.com
